### ISSUE TITLE
Tarea 8

### ISSUE THREAD

**Issue by davidamaro** [JonathanLoz/Fisica-Computacional-Lozano-Mayo#2]
(Ejercicio 1) Te faltó comparar con el resultado teórico.
(Ejercicio 7) Desarrollo completo aunque un poco mal LaTeX: por favor,
utiliza las funciones predefinidas (p.g.$\sinh$ ) de LaTeX.

Te recomiendo [detexify](http://detexify.kirelabs.org/classify.html)

Calificación: 10.

**Comment by JonathanLoz** [comment]
Muchas gracias, buscaré y usaré las funciones de Latex
